---
- name: Starting keepalived container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ keepalived_image_full }}"
    name: "keepalived"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/keepalived/:{{ container_config_directory }}/:ro"
      - "/run:/run"
      - "/lib/modules:/lib/modules:ro"

- name: Starting haproxy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ haproxy_image_full }}"
    name: "haproxy"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/haproxy/:{{ container_config_directory }}/:ro"
      - "/run:/run"

- name: Ensuring latest haproxy config is used
  command: docker exec haproxy /usr/local/bin/kolla_ensure_haproxy_latest_config
  register: status
  changed_when: status.stdout.find('changed') != -1

- name: Waiting for virtual IP to appear
  wait_for: host="{{ kolla_internal_address }}" port="{{ mariadb_port }}"
