---
- name: Starting rabbitmq container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ rabbitmq_image_full }}"
    name: "rabbitmq"
    volumes: "{{ node_config_directory }}/rabbitmq/:{{ container_config_directory }}/:ro"
    volumes_from: "rabbitmq_data"
