---
# enforce ironic usage only with openvswtich
- include: ironic-check.yml

- include: register.yml
  when: inventory_hostname in groups['neutron-server']

- include: config.yml
  when: inventory_hostname in groups['compute'] or
        inventory_hostname in groups['neutron-agents'] or
        inventory_hostname in groups['neutron-server']

- include: config-neutron-fake.yml
  when:
    - inventory_hostname in groups['compute']
    - enable_nova_fake | bool

- include: bootstrap.yml
  when: inventory_hostname in groups['neutron-server']

- include: start.yml
  when: inventory_hostname in groups['compute'] or
        inventory_hostname in groups['neutron-agents'] or
        inventory_hostname in groups['neutron-server']
