---
- name: Allowing non-local IP binding
  sysctl: name="net.ipv4.ip_nonlocal_bind" value=1 sysctl_set=yes
  when: set_sysctl | bool

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "keepalived"
    - "haproxy"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "keepalived"
    - "haproxy"

- name: Copying over haproxy.cfg
  template:
    src: "{{ item }}.cfg.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.cfg"
  with_items:
    - "haproxy"

- name: Copying over keepalived.conf
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.conf"
  with_items:
    - "keepalived"
